apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  selector:
    app: kong
  ports:
    - name: http-traffic
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https-traffic
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http-proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-admin
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: https-admin
      protocol: TCP
      port: 8444
      targetPort: 8444
  type: ClusterIP
